name: Deploy Spring Boot on AWS EC2

on:
  push:
    branches:
      - main  # Change to 'deploy' if using a separate deploy branch
    paths:
      - backend/**

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Ensure gradlew is executable
        run: chmod +x ./backend/gradlew

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/kbm-backend:latest ./backend

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/kbm-backend:latest

      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/kbm-backend:latest
            docker stop kbm-backend || true
            docker rm kbm-backend || true
            docker run -d --name kbm-backend -p 8080:8080 --restart always \
              -e DB_URL=${{ secrets.DB_URL }} \
              -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
              ${{ secrets.DOCKERHUB_USERNAME }}/kbm-backend:latest
